import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { checkout, getPivotMigration, gscAction, listPivotMatches, monitoring, resolvePivotMatch, type PivotMatch } from '../api/pivot';
import { ToolLayout } from './ToolLayout'; import { Button } from './ui/button'; import { Card } from './ui/card'; import { Input } from './ui/input';

export function PivotMigrationDetail() {
  const { migrationId = '' } = useParams(); const [search] = useSearchParams(); const alive = useRef(true);
  const [run,setRun]=useState(''); const [quote,setQuote]=useState(''); const [rows,setRows]=useState<PivotMatch[]>([]); const [next,setNext]=useState<string|null>(null); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const [target,setTarget]=useState<Record<string,string>>({}); const [gsc,setGsc]=useState<{state?:string;properties:Array<{site_url:string}>}>({properties:[]}); const [property,setProperty]=useState(''); const [coverage,setCoverage]=useState<Record<string,unknown>>({}); const [issues,setIssues]=useState<Record<string,unknown>[]>([]); const keys=useRef(new Map<string,string>());
  const key=(intent:string)=>keys.current.get(intent) || (keys.current.set(intent,crypto.randomUUID()),keys.current.get(intent)!);
  const loadRows=useCallback(async(cursor?:string,append=false)=>{if(!run)return;const r=await listPivotMatches(migrationId,run,cursor);if(r.error)throw new Error(r.error.message);if(alive.current){setRows(x=>append?[...x,...(r.data.items||[])]:r.data.items||[]);setNext(r.data.next_cursor||null);}},[migrationId,run]);
  const refresh=useCallback(async()=>{setBusy(true);setMsg('');try{const x=await getPivotMigration(migrationId,search.get('monitoring_id'));if(x.error)throw new Error(x.error.message);const id=String(x.data.run_id||x.data.migration?.run_id||'');setRun(id);setQuote(String(x.data.quote_id||x.data.migration?.quote_id||''));const [mo,fi]=await Promise.all([monitoring(migrationId,false,search.get('monitoring_id')),monitoring(migrationId,true,search.get('monitoring_id'))]);if(mo.error)throw new Error(mo.error.message);if(alive.current){setCoverage(mo.data.coverage||{});setIssues((mo.data.items||fi.data.items||[]) as Record<string,unknown>[]);}}catch(e){if(alive.current)setMsg(e instanceof Error?e.message:'Unable to load migration.');}finally{if(alive.current)setBusy(false);}},[migrationId,search]);
  useEffect(()=>{alive.current=true;void refresh();return()=>{alive.current=false;};},[refresh]); useEffect(()=>{void loadRows();},[loadRows]);
  const decide=async(m:PivotMatch,action:string)=>{setBusy(true);try{const r=await resolvePivotMatch(migrationId,run,{mapping_id:m.mapping_id,expected_revision:m.revision,action,...(action==='set_target'?{target_url:target[m.mapping_id]}:{})},key(`decision:${m.mapping_id}:${m.revision}:${action}`));const outcome=(r.data.outcomes as Array<{code?:string;message?:string}>|undefined)?.[0];if(r.error||outcome?.code&&outcome.code!=='ok')throw new Error(r.error?.message||outcome?.message||outcome?.code||'Decision not saved.');await loadRows();await refresh();}catch(e){setMsg(e instanceof Error?e.message:'Decision not saved.');}finally{setBusy(false);}};
  const gscActionCall=async(action:string)=>{setBusy(true);try{const r=await gscAction({action,migration_id:migrationId,...(action==='sync'?{property}:{})},key(`gsc:${action}:${property}`));if(r.error)throw new Error(r.error.message);if(r.data.authorization_url)window.location.assign(r.data.authorization_url);else {setGsc({state:r.data.connection_state,properties:r.data.properties||[]});setMsg(`Search Console: ${r.data.connection_state||'updated'}.`);}}catch(e){setMsg(e instanceof Error?e.message:'Search Console action failed.');}finally{setBusy(false);}};
  const pay=async()=>{if(!quote)return;setBusy(true);try{const r=await checkout(migrationId,quote);if(r.error)throw new Error(r.error.message);if(r.data.checkout_url)window.location.assign(r.data.checkout_url);else await refresh();}catch(e){setMsg(e instanceof Error?e.message:'Checkout could not start.');}finally{setBusy(false);}};
  return <ToolLayout title="Migration detail"><div className="mx-auto max-w-4xl space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-semibold">Migration detail</h1><p className="text-sm text-muted-foreground">{migrationId}</p></div><Button variant="outline" onClick={()=>void refresh()} disabled={busy}>Refresh status</Button></div>{msg&&<Card className="p-4 text-sm">{msg}</Card>}{quote&&<Card className="p-4"><p className="font-medium">Payment required for this migration.</p><p className="text-sm text-muted-foreground">Price and checkout state are confirmed by the server after return.</p><Button className="mt-3" onClick={()=>void pay()} disabled={busy}>Continue to checkout</Button></Card>}<section><h2 className="mb-3 text-lg font-semibold">Exception review</h2>{rows.map(m=><Card key={m.mapping_id} className="mb-3 p-4"><p className="break-all text-sm">{m.old_url} → {m.decision_target||m.new_url||'No target'}</p><p className="text-xs text-muted-foreground">{m.review_status}; revision {m.revision}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={()=>void decide(m,'approve')} disabled={busy}>Approve</Button><Button size="sm" variant="outline" onClick={()=>void decide(m,'reject')} disabled={busy}>Reject</Button><Input className="h-8 w-52" value={target[m.mapping_id]||''} onChange={e=>setTarget({...target,[m.mapping_id]:e.target.value})} placeholder="Approved target URL"/><Button size="sm" variant="outline" disabled={busy||!target[m.mapping_id]} onClick={()=>void decide(m,'set_target')}>Set target</Button></div></Card>)}{next&&<Button variant="outline" onClick={()=>void loadRows(next,true)}>Load more exceptions</Button>}</section><section className="grid gap-4 md:grid-cols-2"><Card className="p-4"><h2 className="font-semibold">Search Console</h2><p className="mt-1 text-sm text-muted-foreground">{gsc.state||'Not checked'}</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>void gscActionCall('connect')}>Connect</Button><Button size="sm" variant="outline" onClick={()=>void gscActionCall('properties')}>Properties</Button><Button size="sm" variant="outline" onClick={()=>void gscActionCall('sync')} disabled={!property}>Sync</Button></div>{gsc.properties.length>0&&<select className="mt-3 w-full rounded border p-2" value={property} onChange={e=>setProperty(e.target.value)}><option value="">Select property</option>{gsc.properties.map(p=><option key={p.site_url}>{p.site_url}</option>)}</select>}</Card><Card className="p-4"><h2 className="font-semibold">Monitoring</h2><p className="mt-2 text-sm text-muted-foreground">Coverage: {JSON.stringify(coverage)}</p><p className="mt-2 text-sm text-muted-foreground">{issues.length} issue or correction record(s).</p></Card></section></div></ToolLayout>;
}
