import { API_BASE_URL, getAuthHeaders } from './config';
export interface PivotEnvelope<T extends Record<string, unknown> = Record<string, unknown>> { contract_version:string;migration_id:string|null;operation_id:string|null;status:string;next_action:string;data:T;error:{code:string;message:string;retryable:boolean;next_action:string}|null; }
export interface PivotMigration {id:string;name?:string|null;old_origin?:string;new_origin?:string;status?:string;next_action?:string;run_id?:string;quote_id?:string;}
export interface PivotMatch {mapping_id:string;old_url:string;new_url?:string|null;decision_target?:string|null;revision:number;review_status:string;traffic_observed:boolean;traffic_clicks:number|null;}
async function request<T extends Record<string,unknown>>(path:string,init:RequestInit={}):Promise<PivotEnvelope<T>> {const r=await fetch(`${API_BASE_URL}/api/v2${path}`,{...init,headers:{...getAuthHeaders(),...init.headers}});const b=await r.json().catch(()=>null) as PivotEnvelope<T>|null;if(!b||typeof b.data!=='object'||!b.contract_version)throw new Error(r.status===401?'Sign in again to continue.':r.status===404?'This migration was not found.':'Unable to load this migration.');return b;}
export const listPivotMigrations=(cursor?:string)=>request<{items:PivotMigration[];next_cursor?:string|null}>(`/migrations?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
export const getPivotMigration=(id:string,monitoringId?:string|null)=>request<{migration?:PivotMigration;run_id?:string;quote_id?:string}>(`/migrations/${encodeURIComponent(id)}${monitoringId?`?monitoring_id=${encodeURIComponent(monitoringId)}`:''}`);
export const listPivotMatches=(m:string,r:string,cursor?:string)=>request<{items:PivotMatch[];next_cursor?:string|null}>(`/migrations/${m}/runs/${r}/matches?filter=needs_review&limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
export const resolvePivotMatch=(m:string,r:string,d:Record<string,unknown>,idempotencyKey:string)=>request(`/migrations/${m}/runs/${r}/matches`,{method:'PATCH',body:JSON.stringify({decisions:[d],idempotency_key:idempotencyKey})});
export const monitoring=(m:string,fixes=false,monitoringId?:string|null)=>request<{items?:Record<string,unknown>[];coverage?:Record<string,unknown>;next_cursor?:string|null}>(`/migrations/${m}/monitoring${fixes?'/fixes':''}?limit=20${monitoringId?`&monitoring_id=${encodeURIComponent(monitoringId)}`:''}`);
export const gscAction=(d:Record<string,unknown>,idempotencyKey:string)=>request<{authorization_url?:string;connection_state?:string;properties?:Array<{site_url:string}>}>('/connections/search-console/actions',{method:'POST',body:JSON.stringify({...d,idempotency_key:idempotencyKey})});
export const checkout=(m:string,q:string)=>request<{checkout_url?:string}>(`/migrations/${m}/quotes/${q}/checkout`,{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID()})});
export interface SubscriptionCheckout { checkout_id?:string; checkout_url?:string; status?:string; monthly_disclosure?:string; availability?:string; }
export const createSubscriptionCheckout=(body:{sku:'studio'|'monitoring';deployment_id?:string;recurring_consent:true})=>request<SubscriptionCheckout>('/billing/subscription-checkouts',{method:'POST',body:JSON.stringify({...body,idempotency_key:crypto.randomUUID()})});
export const getSubscriptionCheckout=(id:string,returned=false)=>request<SubscriptionCheckout>(`/billing/subscription-checkouts/${encodeURIComponent(id)}${returned?'/return':''}`);
